### ISSUE TITLE
CUDA support

### ISSUE THREAD

**Issue by clarkmcc** [clarkmcc/chitchat#13]
Right now https://github.com/rustformers/llm doesn't support runtime accelerator selection (https://github.com/rustformers/llm/issues/386) which means that the current binaries are metal only for macos, or CPU only for Windows. Until then, maybe we build all Windows binaries for cuda (with feature `cublas`).

**Comment by cchance27** [comment]
Ya i'd definitly say to offer a cuda version, it's basically just adding cublas to the windows llm feature flag :) did it when running it from source and worked great from the look of it.

**Comment by clarkmcc** [comment]
Thanks for testing! I'll get that flag added to the build.
