### ISSUE TITLE
Minor UI/UX and Usability Items...

### ISSUE THREAD

**Issue by cchance27** [clarkmcc/chitchat#16]
Gotta say one of the easiest to get going (once i ran from source due to the other ticket issue lol)

Did notice a few UI/UX issues i wanted to mention that would be cool to see adjusted, not sure if it's windows issues only or all builds but since it's tauri i'd imagine it's the same across all...

1. No way to stop generation, I asked it a question, and wow it was determined to give me the full 2048 response lol and doesn't seem to be a way to stop generation, would be nice if there was a button next to the spinner to kill the current generation somehow. Especially if the LLM starts going down a rabbit hole that doesn't fulfill the original question intension...

2. The left panel could really use a max-width attribute it taking up 50% of the screen on a desktop for settings gets a little silly looking when maximized, in fact after loading the model it could probably collapse to the side behind a hamburger menu to really give a nice feel, as it is now it looks nice when it's small

3. Sending a message scrolls down but doesn't seem to fully scroll to show the message that was sent, it appears to focus at the middle of the first line of text that was sent at the bottom of the window oddly enough.

4. Would be really nice if the interface showed the tokens/s as part of the processing animations, as I noticed something odd and i'm not sure if it's an issue or my imagination, i loaded a model, was generating really fast, changed the system message, and started again and this time it felt slower, but i'm not sure if it actually is or if it's my imagination, and without a readout of tokens/s it's hard to tell.

**Comment by clarkmcc** [comment]
Agreed on all suggestions. 1 may take a little longer, I'll start on 2-4 this next week!
