### ISSUE TITLE
Os error 3 after start

### ISSUE THREAD

**Issue by khannover** [clarkmcc/chitchat#3]
I'm just getting the "os error 3" error code affter launch ("path not found") and i can't do anything inside the app. I've tried the exe and msi installer on german Win11 22H2 Build 22621.1992.

**Comment by clarkmcc** [comment]
Did the error occur when you opened the app, started downloading a model (if so what model?), or when you started promoting the model?

**Comment by clarkmcc** [comment]
Found it, looks like it's crashing when the ~/.chitchat models directory doesn't exist. Fixing now. You can manually create it if you'd like and the app should start up.

**Comment by clarkmcc** [comment]
Resolved for me. Give this [.msi](https://github.com/clarkmcc/chitchat/releases/download/v0.1.1/Chitchat_0.1.1_x64_en-US.msi) a try and let me know if you run into the same error.
